name: Deploy to EC2

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/worry-is-bubble:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/worry-is-bubble:latest

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -i $KEY $USERNAME@$HOST << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/worry-is-bubble:latest
          docker stop worry-is-bubble || true
          docker rm worry-is-bubble || true
          docker run -d --name worry-is-bubble -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/worry-is-bubble:latest
        EOF
